name: Artifact

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: mvn -Dmaven.test.skip=true clean install
      - name: Package
        uses: actions/upload-artifact@main
        with:
          name: vaccineman
          path: target/vaccineman*.jar