name: Java Bot Rest API deploy

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: mvn clean install
      - name: Generate Deployment Package
        run: zip deploy.zip target/vaccineman*.jar
      - name: Get timestamp
          uses: gerred/actions/current-time@master
          id: current-time
      - name: Deploy
          uses: einaregilsson/beanstalk-deploy@v16
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: java-bot-rest-api
            environment_name: prod
            version_label: v
            region: ap-south-1
            deployment_package: deploy.zip